### ISSUE TITLE
Synfig Has No Plugins Folder

### ISSUE THREAD

**Issue by monkeywisdom** [berteh/synfig-import-labels#19]
Hi. I can't find how to install a plugin in Synfig in 2020. I take it the developers stopped maintaining Synfig in 2012. Is that correct? How do I do this on Windows 10?

**Comment by pritam-dey3** [comment]
Synfig is still being maintained actively. However the documentation for synifig is horrible. You can find the plugins folder in windows at `C:\Users\USERNAME\Synfig\plugins`. If you are using a portable version of synfig, you will find it at `ROOT/share/synfig/plugins`

**Comment by berteh** [comment]
Thanks. Documentation had been updated with your explanations at https://github.com/berteh/synfig-import-labels/blob/master/README.md#install

**Comment by berteh** [comment]
Fyi Synfig documentation is getting better:
https://synfig.readthedocs.io/en/latest/plugins.html#how-to-install-plugins
